Cant debug
moon-mail/PyRPOD pull request #56
Opened 2024-03-28 02:09 UTC by JuanPabloRoldan

fixed sweeping of cant angles for DECEL thrusters. also includes visualization

2024-03-28 15:38 UTC, nickpalumbo8 requested changes
1 - New methods in RPOD.py such as visualize_sweep should be listed in the class description’s method list
2 - mdao_unit_test_02.py:
2.1 - should be added to Word document “Test Case Descriptions[NEW]”
2.2 - Update method description “PyRPOD:…” and “Last Changed:…”
3 - Change sweep algorithm to keep each thruster canted the same amount instead of canting one pair through the whole range for each step of the other pair

2024-03-29 09:59 UTC, nickpalumbo8 approved these changes

2024-03-29 13:21 UTC, andytorrestb approved these changes
Ran locally and is passing all test cases.

2024-03-29 20:20 UTC, pearcepatterson approved these changes

2024-03-30 03:52 UTC, nickpalumbo8 approved these changes

2024-03-31 16:38 UTC, closed without merging