Assert statements for rpod_unit_test_01.py
moon-mail/PyRPOD pull request #59
Opened 2024-03-28 16:52 UTC by pearcepatterson

Reorganized test case into setup, execute, assert format. Added assert statements testing functionality of convert_stl_to_vtk().

2024-03-28 18:43 UTC, andytorrestb requested changes
Make sure to add header comment with date changed and Author(s).

Looks good otherwise and runs fine on my machine.

2024-03-28 18:43 UTC, andytorrestb commented on tests/rpod/rpod_unit_test_01.py
Make sure to add header comment with date changed and Author(s).

Looks good otherwise and runs fine on my machine.

2024-03-28 21:51 UTC, andytorrestb approved these changes

2024-03-29 00:51 UTC, JuanPabloRoldan approved these changes

2024-03-29 10:25 UTC, nickpalumbo8 approved these changes
Ran the test case and test_all, looks good.

2024-03-29 10:25 UTC, merged